version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redislabs/rejson:latest
    ports:
      - 6379:6379

  core:
    image: unafamilia/core:latest
    ports:
      - "9000:9000"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_JDBC_DRIVER=org.postgresql.Driver
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db/postgres
      - QUARKUS_PROFILE=dev
      - APPLICATION_WOW_ID=
      - APPLICATION_WOW_SECRET=
    depends_on:
      - db
  events:
    image: unafamilia/events:latest
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_JDBC_DRIVER=org.postgresql.Driver
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db/postgres
    depends_on:
      - db
  orders:
    image: unafamilia/events:latest
    ports:
      - "8082:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_JDBC_DRIVER=org.postgresql.Driver
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db/postgres
    depends_on:
      - db
  wow-api:
    image: unafamilia/wow-api:0.0.1
    ports:
      - "8083:8080"
    environment:
      - BATTLENET_CLIENT_ID=
      - BATTLENET_CLIENT_SECRET=
    depends_on:
      - redis