version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db

  redis:
    image: redislabs/rejson:latest
    ports:
      - 6379:6379
    networks:
      - redis_network

  core:
    image: unafamilia/core:latest
    ports:
      - "9000:9000"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_JDBC_DRIVER=org.postgresql.Driver
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db/postgres
      - QUARKUS_PROFILE=dev
      - QUARKUS_REST_CLIENT_WOW_API_URL=http://wow-api:8080
      - QUARKUS_REST_CLIENT_EVENTS_V1_URL=http://events:8080
      - QUARKUS_REST_CLIENT_ORDERS_V1_URL=http://orders:8080
    env_file:
      - .env
    depends_on:
      - db
      - wow-api
      - events
      - orders
    networks:
      - internal
      - db
  events:
    image: unafamilia/events:latest
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_JDBC_DRIVER=org.postgresql.Driver
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db/postgres
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
    depends_on:
      - db
    networks:
      - db
  orders:
    image: unafamilia/orders:latest
    ports:
      - "8082:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_JDBC_DRIVER=org.postgresql.Driver
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db/postgres
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
    depends_on:
      - db
    networks:
      - db
  wow-api:
    image: unafamilia/wow-api:latest
    ports:
      - "8083:8080"
    environment:
      - REDIS_URL=redis:6379
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - internal
      - redis_network
networks:
  internal:
    name: "internal-network"
  redis_network:
    name: "redis"
  db:
    name: "internal-db"