application:
  discord:
    token: OTAyOTQzNTY5Mjk4NDg5MzY0.YXlxug.dG0hkLC2x5RealQCNH77J0O7XDE
    raidpackage:
      channels:
        initializeOrder: orders-package
        confirmOrder: orders
quarkus:
  datasource:
    db-kind: postgresql
  log:
    level: INFO