application:
  discord:
    origin:
      guild:
        id:
    raidpackage:
      channels:
        initializeOrder: orders-package
        confirmOrder: orders
quarkus:
  oidc:
    auth-server-url: https://eu.battle.net/oauth
    client-id: ${application.wow-api.client-id}
    credentials:
      secret: ${application.wow-api.client-secret}
    authentication:
      error-path: /error
      scopes:
        - 'wow.profile'
    application-type: web-app