application:
  discord:
    origin:
      guild:
        id:
    raidpackage:
      channels:
        initializeOrder: orders-package
        confirmOrder: orders
quarkus:
  datasource:
    db-kind: postgresql
  log:
    level: INFO