application:
  hostname: https://wwww.unafamilia.com
quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://unafamilia.cdjmzmmcesqf.eu-west-2.rds.amazonaws.com:5432/unafamilia
  hibernate-orm:
    database:
      generation: drop-and-create
  oidc:
    auth-server-url: https://eu.battle.net/oauth
    client-id: ${application.wow.id}
    credentials:
      secret: ${application.wow.secret}
    authentication:
      error-path: /error
      scopes:
        - 'wow.profile'
    application-type: web-app
    discord-realm:
      auth-server-url: https://eu.battle.net/oauth
      client-id: ${application.wow.id}
      credentials:
        secret: ${application.wow.secret}