application:
  hostname: "http://localhost:9000"
quarkus:
  rest-client:
    wow-api:
      url: "http://localhost:8080"
      scope: "javax.inject.Singleton"
    events-v1:
      url: "http://localhost:8081"
      scope: "javax.inject.Singleton"
    orders-v1:
      url: "http://localhost:8082"
      scope: "javax.inject.Singleton"
  datasource:
    db-kind: postgresql
    # username: postgres
    # password: mysecretpassword
    # jdbc:
    #   url: jdbc:postgresql://localhost/default
    #   driver: org.postgresql.Driver
  hibernate-orm:
    database:
      generation: drop-and-create
  oidc:
    auth-server-url: https://eu.battle.net/oauth
    client-id: ${application.wow.id}
    credentials:
      secret: ${application.wow.secret}
    authentication:
      error-path: http://localhost:9000/error
      scopes:
        - 'wow.profile'
    application-type: web-app