quarkus:
  http:
    port: 9000
  oidc:
    # keycloak.url is set by OidcWiremockTestResource
    auth-server-url: "${keycloak.url}/realms/quarkus/"
    client-id: quarkus-service-app
    application-type: web_app