application:
  hostname: https://wwww.unafamilia.com
  services:
    audit: "audit-chart"
quarkus:
  rest-client:
    discord-auth:
      url: "https://discord.com/api/v10"
      scope: "javax.inject.Singleton"  
  datasource:
    db-kind: postgresql
    jdbc:
      driver: org.postgresql.Driver
  hibernate-orm:
    database:
      generation: validate
  oidc:
    auth-server-url: https://eu.battle.net/oauth
    client-id: ${application.wow.id}
    credentials:
      secret: ${application.wow.secret}
    authentication:
      error-path: /error
      scopes:
        - 'wow.profile'
    application-type: web-app