application:
  hostname: "http://localhost:9000"
  services:
    audit: "audit:1323"
quarkus:
  rest-client:
    wow-api:
      url: "http://localhost:8083"
      scope: "javax.inject.Singleton"
    wishlist-reporter:
      url: "http://localhost:8084"
      scope: "javax.inject.Singleton"
    discord-auth:
      url: "https://discord.com/api/v10"
      scope: "javax.inject.Singleton"    
  datasource:
    db-kind: postgresql
  hibernate-orm:
    database:
      generation: drop-and-create
  oidc:
    auth-server-url: https://eu.battle.net/oauth
    client-id: ${application.wow.id}
    credentials:
      secret: ${application.wow.secret}
    authentication:
      error-path: http://localhost:9000/error
      scopes:
        - 'wow.profile'
    application-type: web-app 