name: Unafamilia-Core CI

on:
  push:
    paths:
      - 'unafamilia/**'

jobs:
  build_docker_image:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: ${GITHUB_REPOSITORY}/unafamilia-core
      image_tag: ${GITHUB_REF_NAME}
      aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.ECR_ACCESS_KEY_SECRET }}
      aws-region: ${{ env.AWS_REGION }}