name: Unafamilia wow-api

on:
  push:
    paths:
      - 'wow-api/**'

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: unafamilia
  IMAGE_TAG: wow-api

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' 
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_ACCESS_KEY_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build unafamilia-auth -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker logout ${{ steps.login-ecr.outputs.registry }}