name: Deploy Ingress Controller

on: workflow_dispatch
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: apply ingress configuration
        uses: actions-hub/kubectl@master
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f helm-charts/ingress/ingress.yaml