name: Deploy Core App

on: workflow_dispatch
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade core ./helm-charts/java --install --wait --atomic -f ./unafamilia/values.yaml  --set image.tag=$(echo $GITHUB_SHA | head -c7)
          kubeconfig: '${{ secrets.KUBECONFIG }}'
